artifact_location: /home/jinjinjara1022/AutonomousDriving/ObjectDetection/runs/mlflow/0
creation_time: 1754896498055
experiment_id: '0'
last_update_time: 1754896498055
lifecycle_stage: active
name: Default
