artifact_uri: /home/jinjinjara1022/AutonomousDriving/ObjectDetection/runs/mlflow/434999122297909307/bf5b85472f6d41aab50ca7fe67ca0a7c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '434999122297909307'
lifecycle_stage: active
run_id: bf5b85472f6d41aab50ca7fe67ca0a7c
run_name: coco_yv8n
run_uuid: bf5b85472f6d41aab50ca7fe67ca0a7c
source_name: ''
source_type: 4
source_version: ''
start_time: 1754896500937
status: 1
tags: []
user_id: jinjinjara1022
