artifact_location: /home/jinjinjara1022/AutonomousDriving/ObjectTracking/scripts/runs/mlflow/0
creation_time: 1755010405958
experiment_id: '0'
last_update_time: 1755010405958
lifecycle_stage: active
name: Default
